third_party_settings:
  shortcut:
    module_link: true
features:
  node_user_picture: true
  comment_user_picture: true
  comment_user_verification: true
  favicon: true
logo:
  use_default: true
favicon:
  use_default: true
collapsiblock_block: div.block
collapsiblock_title: div.content
collapsiblock_content: ':header:first'
